[package]
name = "ethcontract-derive"
version = "0.1.0"
authors = ["Nicholas Rodrigues Lordello <nlordell@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/gnosis/ethcontract-rs"
homepage = "https://github.com/gnosis/ethcontract-rs"
documentation = "https://docs.rs/ethcontract"
description = """
Proc macro for generating type-safe bindings to Ethereum smart contracts.
"""

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0"
ethabi = "8.0"
ethcontract-common = { path = "../common" }
Inflector = "0.11"
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"
