[package]
name = "examples"
version = "0.0.0"
publish = false
edition = "2018"
license = "MIT OR Apache-2.0"
autobins = false

[dev-dependencies]
ethcontract = { path = "../ethcontract", features = ["derive"] }
futures = "0.3"
tokio = { version = "1.0", features = ["macros"] }
