[package]
name = "ethcontract"
version = "0.15.3"
authors = ["Gnosis developers <developers@gnosis.io>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/gnosis/ethcontract-rs"
homepage = "https://github.com/gnosis/ethcontract-rs"
documentation = "https://docs.rs/ethcontract"
keywords = ["web3", "ethereum", "contract", "async"]
description = """
Runtime library and proc macro for interacting and generating type-safe bindings
to Ethereum smart contracts.
"""

[lib]
name = "ethcontract"

[features]
default = ["derive", "http-tls", "ws-tls-tokio"]
derive = ["ethcontract-derive"]
http = ["web3/http"]
http-tls = ["http", "web3/http-tls"]
http-native-tls = ["http", "web3/http-native-tls"]
http-rustls-tls = ["http", "web3/http-rustls-tls"]
ws-tokio = ["web3/ws-tokio"]
ws-async-std = ["web3/ws-async-std"]
ws-tls-tokio = ["web3/ws-tls-tokio"]
ws-tls-async-std = ["web3/ws-tls-async-std"]
ipc-tokio = ["web3/ipc-tokio"]

[dependencies]
arrayvec = "0.7"
ethcontract-common = { version = "0.15.3", path = "../ethcontract-common" }
ethcontract-derive = { version = "0.15.3", path = "../ethcontract-derive", optional = true}
futures = "0.3"
futures-timer = "3.0"
hex = "0.4"
jsonrpc-core = "18.0"
lazy_static = "1.4"
primitive-types = { version = "0.10", features = ["fp-conversion"] }
secp256k1 = { version = "0.20", features = ["recovery"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
uint = "0.9"
web3 = { git = "https://github.com/tomusdrw/rust-web3.git", rev="a425fa747bca69c7aede4d2c2828f7267d79227e", default-features = false, features = ["signing"] }
zeroize = "1.1"

[dev-dependencies]
hex-literal = "0.3"
tokio = { version = "1.6", features = ["macros"] }
